[licenses]
allow = [
    "AGPL-3.0-or-later",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]

[advisories]
version = 2

[bans]
multiple-versions = "warn"
